services:
  create_superuser:
    build: .
    command: /drf_proxy/create_superuser.sh
    volumes:
      - .:/drf_proxy
    env_file:
      - .env

  web-rest:
    build: .
    command: uvicorn drf_proxy.asgi:application --host 0.0.0.0 --port 8002
    volumes:
      - .:/drf_proxy
    env_file:
      - .env
    ports:
      - "8002:8002"
    depends_on:
      - create_superuser
      - loki
    networks:
      - app_network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}

networks:
  app_network:
    external: true